networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    build:
      context: ./src/monitoring/prometheus
      dockerfile: Dockerfile
      args:
        - PROMETHEUS_MONITOR_LABEL=${PROMETHEUS_MONITOR_LABEL}
        - NODEEXPORTER_PORT=${NODEEXPORTER_PORT}
        - CADVISOR_PORT=${CADVISOR_PORT}
        - PROMETHEUS_PORT=${PROMETHEUS_PORT}
        - PUSHGATEWAY_PORT=${PUSHGATEWAY_PORT}
        - ALERTMANAGER_PORT=${ALERTMANAGER_PORT}
        - NGIX_EXPORTER_PORT=${NGIX_EXPORTER_PORT}
        - EVENT_LOG_PORT=${EVENT_LOG_PORT}
        - PROMETHEUS_RETENTION_TIME=${PROMETHEUS_RETENTION_TIME}
    expose:
      - ${PROMETHEUS_PORT}
    environment:
      - PROMETHEUS_RETENTION_TIME=${PROMETHEUS_RETENTION_TIME}
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitor-net
    restart: ${RESTART_POLICY}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:${PROMETHEUS_PORT}/-/ready",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      org.label-schema.group: "monitoring"

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    volumes:
      - ./src/monitoring/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
    environment:
      - LOKI_HTTP_PORT=${LOKI_PORT}
      - LOKI_GRPC_PORT=${LOKI_GRPC_PORT}
      - LOKI_PATH_PREFIX=${LOKI_PATH_PREFIX}
      - LOKI_REPLICATION_FACTOR=${LOKI_REPLICATION_FACTOR}
      - LOKI_INDEX_PERIOD=${LOKI_INDEX_PERIOD}
      - LOKI_ALERTMANAGER_URL=http://alertmanager:${ALERTMANAGER_PORT}
    restart: ${RESTART_POLICY}
    expose:
      - ${LOKI_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./src/monitoring/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml -config.expand-env=true
    environment:
      - LOKI_PORT=${LOKI_PORT}
    restart: ${RESTART_POLICY}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  alertmanager:
    image: prom/alertmanager:v0.28.0
    container_name: alertmanager
    volumes:
      - ./src/monitoring/alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    restart: ${RESTART_POLICY}
    expose:
      - ${ALERTMANAGER_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v1.8.2
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    restart: ${RESTART_POLICY}
    expose:
      - ${NODEEXPORTER_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: ${RESTART_POLICY}
    expose:
      - ${CADVISOR_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    build:
      context: ./src/monitoring/grafana
      dockerfile: Dockerfile
      args:
        - LOKI_HTTP_PORT=${LOKI_HTTP_PORT}
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${ALLOW_SIGNUP}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
    restart: ${RESTART_POLICY}
    expose:
      - ${GRAFANA_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v1.11.0
    container_name: pushgateway
    restart: ${RESTART_POLICY}
    expose:
      - ${PUSHGATEWAY_PORT}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: caddy:2.9.1
    container_name: caddy
    ports:
      - "${HOST_GRAFANA_PORT}:${HOST_GRAFANA_PORT}"
      - "${HOST_CADVISOR_PORT}:${HOST_CADVISOR_PORT}"
      - "${HOST_PROMETHEUS_PORT}:${HOST_PROMETHEUS_PORT}"
      - "${HOST_ALERTMANAGER_PORT}:${HOST_ALERTMANAGER_PORT}"
      - "${HOST_PUSHGATEWAY_PORT}:${HOST_PUSHGATEWAY_PORT}"
    volumes:
      - ./src/monitoring/caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - HOST_GRAFANA_PORT=${HOST_GRAFANA_PORT}
      - GRAFANA_PORT=${GRAFANA_PORT}
      - HOST_CADVISOR_PORT=${HOST_CADVISOR_PORT}
      - CADVISOR_PORT=${CADVISOR_PORT}
      - HOST_PROMETHEUS_PORT=${HOST_PROMETHEUS_PORT}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - HOST_ALERTMANAGER_PORT=${HOST_ALERTMANAGER_PORT}
      - ALERTMANAGER_PORT=${ALERTMANAGER_PORT}
      - HOST_PUSHGATEWAY_PORT=${HOST_PUSHGATEWAY_PORT}
      - PUSHGATEWAY_PORT=${PUSHGATEWAY_PORT}
    restart: ${RESTART_POLICY}
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
